library(splines2)
library(quadprog)
library(boot)
library(SemiPar)
library(plotrix)

standardize <- function(x, y) {
  sx <- scale(x); sy <- scale(y)
  x_bar <- attr(sx, "scaled:center"); x_sd <- attr(sx, "scaled:scale")
  y_bar <- attr(sy, "scaled:center"); y_sd <- attr(sy, "scaled:scale")
  list(sx = sx, x_bar = x_bar, x_sd = x_sd,
       sy = sy, y_bar = y_bar, y_sd = y_sd)
}

qp_solve <- function(standardized, A_mat, x_mat, ...) {
  d_vec <- with(standardized, crossprod(sx, sy)) 
  D_mat <- crossprod(standardized$sx) 
  sbeta <- quadprog::solve.QP(D_mat, d_vec, A_mat, ...)$solution
  beta0 <- with(standardized,
                as.numeric(crossprod(x_bar * y_sd / x_sd, sbeta)) + y_bar)
  beta1 <- with(standardized, y_sd / x_sd * sbeta)
  list(x_mat = x_mat,
       coefficients = c("(Intercept)" = beta0, beta1),
       fitted = as.numeric(x_mat %*% beta1) + beta0)
}

mono_fit <- function(x, y, monotone = c("increasing", "decreasing"), ...) {
  monotone <- match.arg(monotone)
  x_mat <- iSpline(x, ..., intercept = TRUE)
  standardized <- standardize(x_mat, y) 
  A_mat <- diag(ncol(standardized$sx)) 
  if (monotone == "decreasing") A_mat <- -A_mat  
  qp_solve(standardized, A_mat, x_mat)
}

data(age.income, package = "SemiPar")
dfs <- c(6)
mfits <- lapply(dfs, function(d) {
  with(age.income, mono_fit(age, log.income, df = d))
})

new_x_points = seq(range(age.income$age)[1],range(age.income$age)[2],length = 10)
fit.log.income = rep(NA,length(new_x_points))
for (h in seq_along(new_x_points)){
  
  newx = new_x_points[h]
  new_x = predict(mfits[[1]]$x_mat, newx = newx)
  new_fit = mfits[[1]]$coefficients[1] + sum(mfits[[1]]$coefficients[-1] * new_x)
  fit.log.income[h] = new_fit
  
}

truth = data.frame(age = new_x_points,
                   fit.log.income = fit.log.income,
                   lower = NA,
                   upper = NA)

n <- nrow(age.income)
n_bootstrap <- 1000

for(j in seq_along(new_x_points)){
  
  newx = new_x_points[j]
  boot_means <- rep(NA, n_bootstrap)
  
  for (i in 1:n_bootstrap) {
    boot_indices <- sample(n, replace = TRUE)  
    boot_sample <- age.income[boot_indices, ]  
    mfitss <- lapply(dfs, function(d) {
      with(boot_sample, mono_fit(age, log.income, df = d))
    })
    
    new_x = predict(mfitss[[1]]$x_mat,newx = newx)
    new_fit = mfitss[[1]]$coefficients[1]+sum(mfitss[[1]]$coefficients[-1]*new_x)
    boot_means[i] = as.numeric(new_fit)
  }
  
  CI = quantile(boot_means,probs = c(0.025,0.975))
  truth$lower[j] = CI[1]
  truth$upper[j] = CI[2]
  
}

truth$cover = truth$fit.log.income>truth$lower & truth$fit.log.income<truth$upper
truth

   age         income    lower    upper   cover   SE generated by 1000 bootstrap resampling
1  21.00000       15.34254 13.84109 15.73719  TRUE    0.6699820
2  25.88889       17.18788 15.08217 17.95271  TRUE    0.8516536
3  30.77778       17.33796 15.22696 18.18516  TRUE    0.8718291
4  35.66667       17.34434 15.29922 18.14767  TRUE    0.8359431
5  40.55556       17.34571 15.30806 18.17145  TRUE    0.8719740
6  45.44444       17.34579 15.33284 18.27347  TRUE    0.8557299
7  50.33333       17.34579 15.31484 18.14822  TRUE    0.8721111
8  55.22222       17.34579 15.28231 18.15750  TRUE    0.8618083
9  60.11111       17.34579 15.27811 18.26073  TRUE    0.8716605
10 65.00000       17.34579 15.31106 18.21312  TRUE    0.8671026


library(tidyverse)
ggplot() +
  geom_point(data = age.income,
             mapping = aes(x = age,y = log.income)) +
  geom_point(data = data.frame(age = age.income$age,
                               log.income = mfits[[1]]$fitted),
             mapping = aes(x = age,y = log.income),
             color = 'red') +
  geom_point(data = truth,
             mapping = aes(x = age,y = fit.log.income),
             color = 'blue') +
  geom_errorbar(data = truth,
                mapping = aes(x = age,ymin = lower,ymax = upper),
                width = 1.5) +
  theme_bw()

standard_errors <- rep(NA, length(new_x_points))

for (j in seq_along(new_x_points)) {
  boot_sample_fits <- rep(NA, n_bootstrap)
  
  for (i in 1:n_bootstrap) {
    boot_indices <- sample(n, replace = TRUE)
    boot_sample <- age.income[boot_indices, ]
    mfitss <- lapply(dfs, function(d) {
      with(boot_sample, mono_fit(age, log.income, df = d))
    })
    
    new_x <- predict(mfitss[[1]]$x_mat, newx = new_x_points[j])
    new_fit <- mfitss[[1]]$coefficients[1] + sum(mfitss[[1]]$coefficients[-1] * new_x)
    boot_sample_fits[i] <- as.numeric(new_fit)
  }
  
  standard_errors[j] <- sd(boot_sample_fits)
}

standard_errors
data <- age.income$log.income
n <- length(data)
se <- sd(data) / sqrt(n)
se







n_bootstrap <- 1000
n_points <- length(new_x_points)
cover_results <- matrix(NA, nrow = n_bootstrap, ncol = n_points)

for (i in 1:n_bootstrap) {
  boot_indices <- sample(n, replace = TRUE)
  boot_sample <- age.income[boot_indices, ]
  mfitss <- lapply(dfs, function(d) {
    with(boot_sample, mono_fit(age, log.income, df = d))
  })
  
  for (j in seq_along(new_x_points)) {
    new_x <- predict(mfitss[[1]]$x_mat, newx = new_x_points[j])
    new_fit <- mfitss[[1]]$coefficients[1] + sum(mfitss[[1]]$coefficients[-1] * new_x)
    CI <- quantile(boot_sample_fits, probs = c(0.025, 0.975))
    cover_results[i, j] <- (truth$fit.log.income[j] > CI[1]) & (truth$fit.log.income[j] < CI[2])
  }
}

cover_true_count <- apply(cover_results, 2, function(x) sum(x == TRUE))
cover_false_count <- apply(cover_results, 2, function(x) sum(x == FALSE))

cover_true_count
1000 1000 1000 1000 1000 1000 1000 1000 1000 1000
cover_false_count
0 0 0 0 0 0 0 0 0 0
                           
In 1000 simulation studies, every bootstrap CIs covers the true value generated by the iSpline function                          
                           
                       
